# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: master_server.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='master_server.proto',
  package='master_server',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13master_server.proto\x12\rmaster_server\"\x1d\n\x08\x46ilePath\x12\x11\n\tfile_path\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2X\n\x14MasterServerToClient\x12@\n\x0bGetFileList\x12\x14.master_server.Empty\x1a\x17.master_server.FilePath\"\x00\x30\x01\x62\x06proto3')
)




_FILEPATH = _descriptor.Descriptor(
  name='FilePath',
  full_name='master_server.FilePath',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_path', full_name='master_server.FilePath.file_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=67,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='master_server.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=76,
)

DESCRIPTOR.message_types_by_name['FilePath'] = _FILEPATH
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FilePath = _reflection.GeneratedProtocolMessageType('FilePath', (_message.Message,), dict(
  DESCRIPTOR = _FILEPATH,
  __module__ = 'master_server_pb2'
  # @@protoc_insertion_point(class_scope:master_server.FilePath)
  ))
_sym_db.RegisterMessage(FilePath)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'master_server_pb2'
  # @@protoc_insertion_point(class_scope:master_server.Empty)
  ))
_sym_db.RegisterMessage(Empty)



_MASTERSERVERTOCLIENT = _descriptor.ServiceDescriptor(
  name='MasterServerToClient',
  full_name='master_server.MasterServerToClient',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=78,
  serialized_end=166,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetFileList',
    full_name='master_server.MasterServerToClient.GetFileList',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_FILEPATH,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MASTERSERVERTOCLIENT)

DESCRIPTOR.services_by_name['MasterServerToClient'] = _MASTERSERVERTOCLIENT

# @@protoc_insertion_point(module_scope)
