# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import master_server_pb2 as master__server__pb2


class MasterServerToClientStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetFileList = channel.unary_stream(
        '/master_server.MasterServerToClient/GetFileList',
        request_serializer=master__server__pb2.Empty.SerializeToString,
        response_deserializer=master__server__pb2.FilePath.FromString,
        )


class MasterServerToClientServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetFileList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MasterServerToClientServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetFileList': grpc.unary_stream_rpc_method_handler(
          servicer.GetFileList,
          request_deserializer=master__server__pb2.Empty.FromString,
          response_serializer=master__server__pb2.FilePath.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'master_server.MasterServerToClient', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
