# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import gfs_pb2 as gfs__pb2


class MasterServerToClientStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListFiles = channel.unary_unary(
        '/gfs.MasterServerToClient/ListFiles',
        request_serializer=gfs__pb2.String.SerializeToString,
        response_deserializer=gfs__pb2.String.FromString,
        )
    self.CreateFile = channel.unary_unary(
        '/gfs.MasterServerToClient/CreateFile',
        request_serializer=gfs__pb2.String.SerializeToString,
        response_deserializer=gfs__pb2.String.FromString,
        )


class MasterServerToClientServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListFiles(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateFile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MasterServerToClientServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListFiles': grpc.unary_unary_rpc_method_handler(
          servicer.ListFiles,
          request_deserializer=gfs__pb2.String.FromString,
          response_serializer=gfs__pb2.String.SerializeToString,
      ),
      'CreateFile': grpc.unary_unary_rpc_method_handler(
          servicer.CreateFile,
          request_deserializer=gfs__pb2.String.FromString,
          response_serializer=gfs__pb2.String.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'gfs.MasterServerToClient', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class ChunkServerToClientStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Create = channel.unary_unary(
        '/gfs.ChunkServerToClient/Create',
        request_serializer=gfs__pb2.String.SerializeToString,
        response_deserializer=gfs__pb2.String.FromString,
        )


class ChunkServerToClientServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Create(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ChunkServerToClientServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Create': grpc.unary_unary_rpc_method_handler(
          servicer.Create,
          request_deserializer=gfs__pb2.String.FromString,
          response_serializer=gfs__pb2.String.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'gfs.ChunkServerToClient', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
