# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import gfs_pb2 as gfs__pb2


class MasterServerToClientStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListFiles = channel.unary_unary(
        '/gfs.MasterServerToClient/ListFiles',
        request_serializer=gfs__pb2.String.SerializeToString,
        response_deserializer=gfs__pb2.String.FromString,
        )
    self.CreateFile = channel.unary_unary(
        '/gfs.MasterServerToClient/CreateFile',
        request_serializer=gfs__pb2.String.SerializeToString,
        response_deserializer=gfs__pb2.String.FromString,
        )
    self.AppendFile = channel.unary_unary(
        '/gfs.MasterServerToClient/AppendFile',
        request_serializer=gfs__pb2.String.SerializeToString,
        response_deserializer=gfs__pb2.String.FromString,
        )
    self.CreateChunk = channel.unary_unary(
        '/gfs.MasterServerToClient/CreateChunk',
        request_serializer=gfs__pb2.String.SerializeToString,
        response_deserializer=gfs__pb2.String.FromString,
        )
    self.ReadFile = channel.unary_unary(
        '/gfs.MasterServerToClient/ReadFile',
        request_serializer=gfs__pb2.String.SerializeToString,
        response_deserializer=gfs__pb2.String.FromString,
        )
    self.DeleteFile = channel.unary_unary(
        '/gfs.MasterServerToClient/DeleteFile',
        request_serializer=gfs__pb2.String.SerializeToString,
        response_deserializer=gfs__pb2.String.FromString,
        )
    self.UndeleteFile = channel.unary_unary(
        '/gfs.MasterServerToClient/UndeleteFile',
        request_serializer=gfs__pb2.String.SerializeToString,
        response_deserializer=gfs__pb2.String.FromString,
        )


class MasterServerToClientServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListFiles(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateFile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AppendFile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateChunk(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReadFile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteFile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UndeleteFile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MasterServerToClientServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListFiles': grpc.unary_unary_rpc_method_handler(
          servicer.ListFiles,
          request_deserializer=gfs__pb2.String.FromString,
          response_serializer=gfs__pb2.String.SerializeToString,
      ),
      'CreateFile': grpc.unary_unary_rpc_method_handler(
          servicer.CreateFile,
          request_deserializer=gfs__pb2.String.FromString,
          response_serializer=gfs__pb2.String.SerializeToString,
      ),
      'AppendFile': grpc.unary_unary_rpc_method_handler(
          servicer.AppendFile,
          request_deserializer=gfs__pb2.String.FromString,
          response_serializer=gfs__pb2.String.SerializeToString,
      ),
      'CreateChunk': grpc.unary_unary_rpc_method_handler(
          servicer.CreateChunk,
          request_deserializer=gfs__pb2.String.FromString,
          response_serializer=gfs__pb2.String.SerializeToString,
      ),
      'ReadFile': grpc.unary_unary_rpc_method_handler(
          servicer.ReadFile,
          request_deserializer=gfs__pb2.String.FromString,
          response_serializer=gfs__pb2.String.SerializeToString,
      ),
      'DeleteFile': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteFile,
          request_deserializer=gfs__pb2.String.FromString,
          response_serializer=gfs__pb2.String.SerializeToString,
      ),
      'UndeleteFile': grpc.unary_unary_rpc_method_handler(
          servicer.UndeleteFile,
          request_deserializer=gfs__pb2.String.FromString,
          response_serializer=gfs__pb2.String.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'gfs.MasterServerToClient', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class ChunkServerToClientStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Create = channel.unary_unary(
        '/gfs.ChunkServerToClient/Create',
        request_serializer=gfs__pb2.String.SerializeToString,
        response_deserializer=gfs__pb2.String.FromString,
        )
    self.GetChunkSpace = channel.unary_unary(
        '/gfs.ChunkServerToClient/GetChunkSpace',
        request_serializer=gfs__pb2.String.SerializeToString,
        response_deserializer=gfs__pb2.String.FromString,
        )
    self.Append = channel.unary_unary(
        '/gfs.ChunkServerToClient/Append',
        request_serializer=gfs__pb2.String.SerializeToString,
        response_deserializer=gfs__pb2.String.FromString,
        )
    self.Read = channel.unary_unary(
        '/gfs.ChunkServerToClient/Read',
        request_serializer=gfs__pb2.String.SerializeToString,
        response_deserializer=gfs__pb2.String.FromString,
        )


class ChunkServerToClientServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Create(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetChunkSpace(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Append(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Read(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ChunkServerToClientServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Create': grpc.unary_unary_rpc_method_handler(
          servicer.Create,
          request_deserializer=gfs__pb2.String.FromString,
          response_serializer=gfs__pb2.String.SerializeToString,
      ),
      'GetChunkSpace': grpc.unary_unary_rpc_method_handler(
          servicer.GetChunkSpace,
          request_deserializer=gfs__pb2.String.FromString,
          response_serializer=gfs__pb2.String.SerializeToString,
      ),
      'Append': grpc.unary_unary_rpc_method_handler(
          servicer.Append,
          request_deserializer=gfs__pb2.String.FromString,
          response_serializer=gfs__pb2.String.SerializeToString,
      ),
      'Read': grpc.unary_unary_rpc_method_handler(
          servicer.Read,
          request_deserializer=gfs__pb2.String.FromString,
          response_serializer=gfs__pb2.String.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'gfs.ChunkServerToClient', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
