# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gfs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gfs.proto',
  package='gfs',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tgfs.proto\x12\x03gfs\"\x14\n\x06String\x12\n\n\x02st\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xbc\x02\n\x14MasterServerToClient\x12\'\n\tListFiles\x12\x0b.gfs.String\x1a\x0b.gfs.String\"\x00\x12(\n\nCreateFile\x12\x0b.gfs.String\x1a\x0b.gfs.String\"\x00\x12(\n\nAppendFile\x12\x0b.gfs.String\x1a\x0b.gfs.String\"\x00\x12)\n\x0b\x43reateChunk\x12\x0b.gfs.String\x1a\x0b.gfs.String\"\x00\x12&\n\x08ReadFile\x12\x0b.gfs.String\x1a\x0b.gfs.String\"\x00\x12(\n\nDeleteFile\x12\x0b.gfs.String\x1a\x0b.gfs.String\"\x00\x12*\n\x0cUndeleteFile\x12\x0b.gfs.String\x1a\x0b.gfs.String\"\x00\x32\xb2\x01\n\x13\x43hunkServerToClient\x12$\n\x06\x43reate\x12\x0b.gfs.String\x1a\x0b.gfs.String\"\x00\x12+\n\rGetChunkSpace\x12\x0b.gfs.String\x1a\x0b.gfs.String\"\x00\x12$\n\x06\x41ppend\x12\x0b.gfs.String\x1a\x0b.gfs.String\"\x00\x12\"\n\x04Read\x12\x0b.gfs.String\x1a\x0b.gfs.String\"\x00\x62\x06proto3')
)




_STRING = _descriptor.Descriptor(
  name='String',
  full_name='gfs.String',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='st', full_name='gfs.String.st', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=38,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='gfs.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=47,
)

DESCRIPTOR.message_types_by_name['String'] = _STRING
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

String = _reflection.GeneratedProtocolMessageType('String', (_message.Message,), dict(
  DESCRIPTOR = _STRING,
  __module__ = 'gfs_pb2'
  # @@protoc_insertion_point(class_scope:gfs.String)
  ))
_sym_db.RegisterMessage(String)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'gfs_pb2'
  # @@protoc_insertion_point(class_scope:gfs.Empty)
  ))
_sym_db.RegisterMessage(Empty)



_MASTERSERVERTOCLIENT = _descriptor.ServiceDescriptor(
  name='MasterServerToClient',
  full_name='gfs.MasterServerToClient',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=50,
  serialized_end=366,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListFiles',
    full_name='gfs.MasterServerToClient.ListFiles',
    index=0,
    containing_service=None,
    input_type=_STRING,
    output_type=_STRING,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateFile',
    full_name='gfs.MasterServerToClient.CreateFile',
    index=1,
    containing_service=None,
    input_type=_STRING,
    output_type=_STRING,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AppendFile',
    full_name='gfs.MasterServerToClient.AppendFile',
    index=2,
    containing_service=None,
    input_type=_STRING,
    output_type=_STRING,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateChunk',
    full_name='gfs.MasterServerToClient.CreateChunk',
    index=3,
    containing_service=None,
    input_type=_STRING,
    output_type=_STRING,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ReadFile',
    full_name='gfs.MasterServerToClient.ReadFile',
    index=4,
    containing_service=None,
    input_type=_STRING,
    output_type=_STRING,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteFile',
    full_name='gfs.MasterServerToClient.DeleteFile',
    index=5,
    containing_service=None,
    input_type=_STRING,
    output_type=_STRING,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UndeleteFile',
    full_name='gfs.MasterServerToClient.UndeleteFile',
    index=6,
    containing_service=None,
    input_type=_STRING,
    output_type=_STRING,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MASTERSERVERTOCLIENT)

DESCRIPTOR.services_by_name['MasterServerToClient'] = _MASTERSERVERTOCLIENT


_CHUNKSERVERTOCLIENT = _descriptor.ServiceDescriptor(
  name='ChunkServerToClient',
  full_name='gfs.ChunkServerToClient',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=369,
  serialized_end=547,
  methods=[
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='gfs.ChunkServerToClient.Create',
    index=0,
    containing_service=None,
    input_type=_STRING,
    output_type=_STRING,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetChunkSpace',
    full_name='gfs.ChunkServerToClient.GetChunkSpace',
    index=1,
    containing_service=None,
    input_type=_STRING,
    output_type=_STRING,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Append',
    full_name='gfs.ChunkServerToClient.Append',
    index=2,
    containing_service=None,
    input_type=_STRING,
    output_type=_STRING,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Read',
    full_name='gfs.ChunkServerToClient.Read',
    index=3,
    containing_service=None,
    input_type=_STRING,
    output_type=_STRING,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHUNKSERVERTOCLIENT)

DESCRIPTOR.services_by_name['ChunkServerToClient'] = _CHUNKSERVERTOCLIENT

# @@protoc_insertion_point(module_scope)
